[project]
name = "jbi"  # Replace with your package name
version = "0.1.0"  # Replace with your package version
readme = "README.md" 
authors = [
  {name = "Ramon Correa-Medero", email = "correa.ramon14@gmail.com" }
] 
maintainers = [
  {name = "Ramon Correa-Medero", email = "correa.ramon14@egmail.com" }
]

requires-python = '>=3.10'

dependencies = [
"numpy==1.26.4",
"pillow==11.3.0",
"pip==25.2",
"setuptools==80.9.0",
"sympy==1.14.0",
"torch==2.8.0",
"torchcam==0.4.0",
"wheel==0.45.1",
"torchvision==0.23.0",
"scikit-learn==1.7.1",
"optuna==4.5.0"
]
